# Generated by Django 5.2.14 on 2026-06-08 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("base", "0029_alter_product_free_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PostTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("template_text", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_templates",
                        to="base.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post Template",
                "verbose_name_plural": "Post Templates",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ScheduleRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("before_event", "Before Event Starts"),
                            ("after_event", "After Event Ends"),
                            ("before_session", "Before Session Starts"),
                            ("after_session", "After Session Ends"),
                        ],
                        max_length=30,
                        verbose_name="Trigger Type",
                    ),
                ),
                (
                    "offset_minutes",
                    models.IntegerField(verbose_name="Offset (in minutes)"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_schedule_rules",
                        to="base.event",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_rules",
                        to="socialmedia.posttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule Rule",
                "verbose_name_plural": "Schedule Rules",
                "ordering": ("offset_minutes",),
            },
        ),
        migrations.CreateModel(
            name="SocialMediaAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=50)),
                ("account_name", models.CharField(max_length=255)),
                ("credentials", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to="base.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Media Account",
                "verbose_name_plural": "Social Media Accounts",
                "unique_together": {("event", "provider", "account_name")},
            },
        ),
        migrations.CreateModel(
            name="SocialPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "media",
                    models.FileField(
                        blank=True, null=True, upload_to="socialmedia/posts/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("scheduled", "Scheduled"),
                            ("publishing", "Publishing"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("published_time", models.DateTimeField(blank=True, null=True)),
                (
                    "external_post_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to="socialmedia.socialmediaaccount",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_posts",
                        to="base.event",
                    ),
                ),
                (
                    "talk_slot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="social_posts",
                        to="base.talkslot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Post",
                "verbose_name_plural": "Social Posts",
                "ordering": ("-scheduled_time",),
            },
        ),
        migrations.CreateModel(
            name="SocialPostAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("from_status", models.CharField(blank=True, max_length=50, null=True)),
                ("to_status", models.CharField(blank=True, max_length=50, null=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="socialmedia.socialpost",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="social_post_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Post Audit Log",
                "verbose_name_plural": "Social Post Audit Logs",
                "ordering": ("-timestamp",),
            },
        ),
    ]
